#!/bin/bash

DATE=$(date +'%H:%M:%S')

for i in {1..10}
do 
date +'%H:%M:%S'
ps -f | grep -vw UID | wc -l

sleep 5
done

cat /proc/cpuinfo | grep -w vendor_id >> /opt/280223_m/Anton_Cheprasov/cpuinfo.txt
cat /proc/cpuinfo | grep '^NAME=' | cut -d= -f2 > /opt/280223_m/Anton_Cheprasov/cpuinfo.txt

for ((i=50;i<=100;i++)); do
    touch "${i}.txt"
done
